import Link from 'next/link';

export default function HowItWorks() {
  return (
    <main className="mx-auto max-w-2xl p-6 md:p-10">
      <Link href="/" className="text-sm text-gray-500 underline hover:text-gray-300">
        ← home
      </Link>
      <h1 className="mt-6 text-3xl font-bold">How it works</h1>

      <section className="mt-8 space-y-3">
        <h2 className="text-xl font-bold text-orange-500">The game</h2>
        <p className="text-gray-300">
          You get three 3-letter IATA airport codes a day, easy → medium → hard. Tap where each
          airport is on the satellite globe. Your score for each guess falls off exponentially with
          distance from the real airport.
        </p>
        <p className="text-gray-300">
          Everyone plays the same three airports each day. A new round drops at 00:00 UTC-5. v1 is
          US airports only.
        </p>
      </section>

      <section className="mt-8 space-y-3">
        <h2 className="text-xl font-bold text-orange-500">Scoring</h2>
        <pre className="rounded bg-zinc-900 p-3 font-mono text-sm text-gray-300">
          score = round(5000 × exp(−distance_mi / 750))
        </pre>
        <p className="text-gray-300">Max 5,000 points per question, 15,000 per round.</p>
        <table className="mt-2 w-full max-w-sm text-sm">
          <thead>
            <tr className="text-left text-xs uppercase tracking-widest text-gray-500">
              <th className="pb-2 pr-6 font-normal">Distance</th>
              <th className="pb-2 font-normal">Score</th>
            </tr>
          </thead>
          <tbody className="font-mono text-gray-300">
            <tr><td className="py-0.5">0 mi</td><td>5,000</td></tr>
            <tr><td className="py-0.5">50 mi</td><td>4,678</td></tr>
            <tr><td className="py-0.5">250 mi</td><td>3,583</td></tr>
            <tr><td className="py-0.5">500 mi</td><td>2,567</td></tr>
            <tr><td className="py-0.5">1,000 mi</td><td>1,318</td></tr>
            <tr><td className="py-0.5">2,000 mi</td><td>347</td></tr>
            <tr><td className="py-0.5">5,000 mi</td><td>6</td></tr>
          </tbody>
        </table>
      </section>

      <section className="mt-8 space-y-3">
        <h2 className="text-xl font-bold text-orange-500">Tiers</h2>
        <p className="text-gray-300">The three questions get progressively harder.</p>
        <ul className="space-y-1 text-gray-300">
          <li>
            <strong className="text-white">Easy</strong> — major US hubs (JFK, LAX, ORD, ATL, …).
          </li>
          <li>
            <strong className="text-white">Medium</strong> — secondary metros and well-known
            regionals (SAT, SMF, ANC, MSY, …).
          </li>
          <li>
            <strong className="text-white">Hard</strong> — anywhere with scheduled service: small
            regionals, Alaska bush airfields, Pacific islands.
          </li>
        </ul>
      </section>

      <section className="mt-8 space-y-3">
        <h2 className="text-xl font-bold text-orange-500">Privacy</h2>
        <p className="text-gray-300">
          No accounts, no email, no tracking pixels. The only identifier is a UUID generated by your
          browser and stored in <code className="font-mono text-gray-200">localStorage</code>. Clear
          your browser data and you&apos;re a new player.
        </p>
      </section>

      <div className="mt-12 flex gap-6 text-sm text-gray-500">
        <Link href="/play" className="text-orange-500 underline hover:text-orange-400">
          Play today&apos;s round
        </Link>
        <Link href="/stats" className="underline hover:text-gray-300">
          Your stats
        </Link>
      </div>
    </main>
  );
}
